import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const coolvetiSans = localFont({
  src: "./fonts/CoolveticaRg.ttf",
  variable: "--font-coolveti-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${coolvetiSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
